{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-affinity-guard
  namespace: {{ .Values.monitorResource.namespace }}
subjects:
- kind: ServiceAccount
  name: node-affinity-guard
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
{{- end -}}